[package]
name = "test-crate"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
libz-sys = { version = "1.1.19", default-features = false, features = ["zlib-ng"] }

[patch.crates-io]
cmake = { path = ".." }
